#!/usr/bin/env bash
# Displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=':' read -r username info home passwd uid gid shell; do
  echo "The user $username is part of the $gid gang,"\
  "lives in $home and rides $shell."\
  "$uid's place is protected by the passcode $passwd,"\
  "more info about the user here: $info"
done < "/etc/passwd"
